services:
  moonchausen-db:
    container_name: moonchausen-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: always
    env_file: ./cms/.env
    image: postgres:14.5-alpine
    volumes:
      - moonchausen-cms-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - moonchausen-network

  moonchausen-cms:
    container_name: moonchausen-cms
    build:
      context: ./cms
      dockerfile: ./Dockerfile
    image: moonchausen-cms:latest
    restart: always
    env_file: ./cms/.env
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/yarn.lock:/opt/yarn.lock
      - ./cms/.env:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - 1337:1337
    networks:
      - moonchausen-network

  moonchausen-web:
    container_name: moonchausen-web
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: moonchausen-web:latest
    restart: always
    working_dir: /app
    env_file: ./web/.env
    volumes:
      - ./web/src:/app/src
      - ./web/package.json:/package.json
      - ./web/pnpm-lock.yaml:/pnpm-lock.yaml
      - ./web/next.config.js:/next.config.js
      - ./web/.next:/.next
    ports:
      - 3000:3000
    networks:
      - moonchausen-network

volumes:
  moonchausen-cms-data:

networks:
  moonchausen-network:
    name: moonchausen-network
    driver: bridge