version: "3.9"

services:
  moonchausen-cms-db:
    container_name: moonchausen-cms-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: ./cms/.env
    image: postgres:14.5-alpine
    volumes:
      - moonchausen-cms-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    networks:
      - moonchausen-network
      
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    working_dir: /app
    env_file: ./frontend/.env
    ports:
      - 3000:3000
    networks:
      - moonchausen-network
    depends_on:
      - moonchausen-cms

  moonchausen-cms:
    container_name: moonchausen-cms
    build:
      context: ./cms
      dockerfile: ./Dockerfile
    image: moonchausen-cms:latest
    restart: unless-stopped
    env_file: ./cms/.env
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./cms/yarn.lock:/opt/yarn.lock
      - ./cms/.env:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    networks:
      - moonchausen-network
    depends_on:
      - moonchausen-cms-db

volumes:
  moonchausen-cms-data:

networks:
  moonchausen-network:
    name: moonchausen-network
    driver: bridge